- hosts: nexus
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Create Nexus data dir
      file:
        path: /opt/nexus-data
        state: directory
        owner: 200
        group: 200
        mode: '0755'

    - name: Run Nexus container
      community.docker.docker_container:
        name: nexus
        image: sonatype/nexus3:3.82.0
        restart_policy: always
        published_ports:
          - "8081:8081"   # Nexus UI/API
          - "5000:5000"   # Docker registry
        volumes:
          - /opt/nexus-data:/nexus-data
